### ISSUE TITLE
是否要 cache 住 PPAV 這個指令會取的前五十片

### ISSUE THREAD

**Issue by homerchen19** [PPAV-inc/telegram-bot#10]
用 `Redis`

**Comment by LittleWhiteYA** [comment]
可    不過 Server 環境要先搞定就是了
如果還是用 heroku 的話
Redis 有免費額度嗎...？

**Comment by homerchen19** [comment]
之後估計會改到 AWS 上，有錢之後也可以用租的
Redis 就可以裝在 VM 上了

**Comment by LittleWhiteYA** [comment]
https://github.com/isaacs/node-lru-cache

討論過用這個搞不好更簡單

**Comment by LittleWhiteYA** [comment]
先 close，感覺先不用
