### ISSUE TITLE
img_url 是 null

### ISSUE THREAD

**Issue by homerchen19** [PPAV-inc/telegram-bot#117]
資料庫裡的 `img_url` 有可能是 null
https://github.com/PPAV-inc/telegram-bot/blob/master/src/bot/utils/getKeyboardSettings.js#L100

https://github.com/PPAV-inc/telegram-bot/blob/master/src/bot/middleware/sendMessageMiddleware.js#L39
這裡會判斷圖片網址是不是 null，
如果有搜到片，但圖片網址卻是 null 時會造成傳不出去的問題
目前是先用隨便一張預設圖片擋一下，
要看是爬蟲的問題還是要有個更正式的預設圖

**Comment by LittleWhiteYA** [comment]
你暫時上的圖的那個 PR 要不要送上來0.0？

**Comment by LittleWhiteYA** [comment]
解決ㄌ
