### ISSUE TITLE
DB 清掉 users 後會炸掉

### ISSUE THREAD

**Issue by homerchen19** [PPAV-inc/telegram-bot#44]
估計是因為沒有從頭（/start）來，
所以使用者資料沒有在其他地方放進 DB，
導致查不到而炸掉

**Comment by LittleWhiteYA** [comment]
這不知道算不算 bug
因為以後應該不會有清掉這個動作
頂多做 migrate

**Comment by homerchen19** [comment]
Poller 也有做預防，所以我覺得寫個預防沒關係
