### ISSUE TITLE
待解決問題

### ISSUE THREAD

**Issue by aresyuan** [PPAV-inc/telegram-bot#52]
用戶有可能會忽略隨機選片功能（輸入PPAV），討論是否更改描述。

<img width="509" alt="2017-08-19 22 53 38" src="https://user-images.githubusercontent.com/5604087/29487959-49799b5e-8534-11e7-8274-b4c898f9a979.png">

**Comment by homerchen19** [comment]
#25 之一

**Comment by homerchen19** [comment]
最新版改成這樣
<img width="470" alt="screen shot 2017-09-01 at 6 42 00 pm" src="https://user-images.githubusercontent.com/12113222/29966612-461bd8c6-8f45-11e7-81a2-324a9ef45451.png">
