### ISSUE TITLE
logs collection

### ISSUE THREAD

**Issue by LittleWhiteYA** [PPAV-inc/telegram-bot#61]
存使用者 query 的全部資料
包含有搜尋到結果 and 沒搜尋到結果

**Comment by homerchen19** [comment]
目前 query 的全部資料 dashbot 那邊都有記錄到
先 close 掉？

**Comment by LittleWhiteYA** [comment]
這部分我想找出使用者沒搜尋到的結果
dashbot 可以做到？

**Comment by homerchen19** [comment]
dashbot 只有記錄全部的 io
有沒有搜尋到他不會知道，只能我們另外存
