### ISSUE TITLE
使用者體驗改善：「很抱歉，搜尋不到結果」

### ISSUE THREAD

**Issue by aresyuan** [PPAV-inc/telegram-bot#64]
在沒有找到任何搜尋結果的狀況（女優、標題、tag），可否加入一些其他建議清單，像是：
1. 現有的熱門tag標籤
2. 現有的熱門影片連結

等等之類的結果，反正就吐出一些東西，讓使用者有其他搜尋選擇～

**Comment by LittleWhiteYA** [comment]
熱門標籤應該做不到了
因為換到 ES 上
我吐熱門影片好了

不過在剛開始我還是會吐 "很抱歉，搜尋不到結果"
